import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "네이버 급매물 정보",
  description: "Generated by AURAWORKS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='main-container'>
        <Navbar></Navbar>

          {children}
        
      </body>
    </html>
  );
}
